name: Build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: windows-latest
    name: Testing
    steps:
      - name: Checkout code base
        uses: actions/checkout@v3

      - name: Run tests
        run: dotnet test --verbosity normal --configuration Release

  build:
    runs-on: windows-latest
    name: Building
    steps:
      - name: Checkout code base
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: dotnet restore PAMU_CDS.sln /p:Configuration=Release

      - name: Run tests
        run: dotnet test --verbosity normal --configuration Release

      - name: Build solution
        run: msbuild /p:OutputPath=../build /p:Configuration=Release /p:RestorePackages=false

      - name: Archive build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/PAMU_CDS.dll   
          retention-days: 5